name: Check Code Quality

on:
  push:
  workflow_dispatch:

jobs:
  check-code-quality:
    name: Check Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Run Checks
        run: gradle lintDebug koverVerify koverHtmlReport --parallel --build-cache

      - name: Upload Kover Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kover-report
          path: composeApp/build/reports/kover/html/

      - name: Deploy Kover Report to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: composeApp/build/reports/kover/html
          destination_dir: coverage

      - name: Print Hosted Report URL
        if: github.ref == 'refs/heads/master'
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          echo "Hosted Kover Report: https://${{ github.repository_owner }}.github.io/$REPO_NAME/coverage/"

