name: CI/CD Pipeline

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  check:
    name: Check Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Run Checks
        run: gradle lintDebug koverVerify koverHtmlReport --parallel --build-cache

      - name: Upload Kover Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kover-report
          path: composeApp/build/reports/kover/html/

      - name: Deploy Kover Report to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: composeApp/build/reports/kover/html
          destination_dir: coverage

      - name: Print Hosted Report URL
        if: github.ref == 'refs/heads/master'
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          echo "Hosted Kover Report: https://${{ github.repository_owner }}.github.io/$REPO_NAME/coverage/"

  build-android-debug:
    name: Build Android App
    needs: [check]
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Build Android App
        run: gradle assembleDebug --parallel --build-cache

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: '**/build/outputs/apk/debug/*.apk'

#  build-ios-debug:
#    name: Build iOS App
#    needs: [check]
#    runs-on: macos-latest
#    environment: production
#    timeout-minutes: 45
#
#    steps:
#      - name: Setup Environment
#        uses: ./.github/actions/setup-env
#
#      - name: Build Kotlin Framework for iOS
#        run: gradle :composeApp:linkDebugFrameworkIosSimulatorArm64 --parallel --build-cache
#
#      - name: Build iOS App
#        run: |
#          cd iosApp
#          xcodebuild -project iosApp.xcodeproj \
#            -scheme iosApp \
#            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
#            clean build \
#            CODE_SIGNING_ALLOWED=NO

  build-android-release:
    name: Build Android App (Release)
    needs: [check]
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Build Android App
        run: gradle assembleRelease --parallel --build-cache

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: '**/build/outputs/apk/release/*.apk'

#  build-ios-release:
#    name: Build iOS App (Release)
#    needs: [check]
#    runs-on: macos-latest
#    environment: production
#    timeout-minutes: 45
#
#    steps:
#      - name: Setup Environment
#        uses: ./.github/actions/setup-env
#
#      - name: Build Kotlin Framework for iOS
#        run: gradle :composeApp:linkReleaseFrameworkIosSimulatorArm64 --parallel --build-cache
#
#      - name: Build iOS App
#        run: |
#          cd iosApp
#          xcodebuild -project iosApp.xcodeproj \
#            -scheme iosApp \
#            -configuration Release \
#            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
#            clean build \
#            CODE_SIGNING_ALLOWED=NO

